Numerical library in python which deals with arrays in python. Array is collection of data, the data should be heterogenous. ( A list could have different data types. but in array, technically we should have only one data type)

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array(list('abcde'))

print(arr1)
print(arr2)
# there is still no difference if the array here (which looks like a list) has no comma. It's just the representa-
#tion of array and nothing more

[1 2 3 4]
['a' 'b' 'c' 'd' 'e']


In [2]:
print(arr1.dtype)

int64


In [3]:
print(arr2.dtype)
# string is denoted as U1 in numpy

<U1


In [5]:
lst1 = [1, 'a', 2 + 3j, (2, 3)]
print(lst1)
print(type(lst1))

[1, 'a', (2+3j), (2, 3)]
<class 'list'>


In [7]:
arr3 = np.array(lst1)
print(arr3)
print(arr3.dtype)
# we are able to create an array with heterogenous data, the array is in form of object data type.
# It does show a warning error
# Technically though we only have one datatype( try not to make an array with different datatypes)

[1 'a' (2+3j) (2, 3)]
object


/var/folders/01/wbf4q7254sg4vtt9f05q1z8r0000gn/T/ipykernel_3185/2432220898.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array(lst1)


- > In arrays, the elements in each dimension should be the same- on particular axis
- In numpy, the metadata (memory location) is stored in the numpy array object itself. 
- In numpy, the data is stored in contigous block of memory -- any memory block that is adjacent to the last memory block. can be any one of the four. 
- for the execution, if the element does not find any adjacent block of memory, then it waits till it gets enough memory to process the array

- we use numpy arrays because
1. They are very fast than the list objects.
2. They offer us efficient way of doing mathematical operations. 

In [8]:
import numpy as np

nump_a = np.arange(10000000)
list_a = list(range(10000000))

print(len(nump_a))
print(len(list_a))

10000000
10000000


In [10]:
%%time

list_b = [i * 2 for i in list_a]

CPU times: user 359 ms, sys: 103 ms, total: 462 ms
Wall time: 475 ms


In [12]:
%%time

nump_a = nump_a * 2

# in numpy we don't have to do any for loop, we can just multiple the whole array by 2 that is applicable to all
# the elements

CPU times: user 88.8 ms, sys: 191 ms, total: 279 ms
Wall time: 313 ms


In [14]:
arr = np.arange(10, dtype = float)
print(arr)
print(type(arr)) # type of object arr
print(arr.dtype)  #  type of data in arr

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
float64


In [ ]:
# arange in numpy version of range

In [15]:
arr1 = np.array([5,7,9,11])
print(arr1)

[ 5  7  9 11]


In [19]:
data = np.arange(6).reshape(3,2)
print(data)
print(data.shape)
print(data.ndim) # to check number of dimensions

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2


In [21]:
data1 = np.arange(720).reshape(2,3,4,5,6)
print(data1)
print(data1.shape)
print(data1.ndim)

[[[[[  0   1   2   3   4   5]
    [  6   7   8   9  10  11]
    [ 12  13  14  15  16  17]
    [ 18  19  20  21  22  23]
    [ 24  25  26  27  28  29]]

   [[ 30  31  32  33  34  35]
    [ 36  37  38  39  40  41]
    [ 42  43  44  45  46  47]
    [ 48  49  50  51  52  53]
    [ 54  55  56  57  58  59]]

   [[ 60  61  62  63  64  65]
    [ 66  67  68  69  70  71]
    [ 72  73  74  75  76  77]
    [ 78  79  80  81  82  83]
    [ 84  85  86  87  88  89]]

   [[ 90  91  92  93  94  95]
    [ 96  97  98  99 100 101]
    [102 103 104 105 106 107]
    [108 109 110 111 112 113]
    [114 115 116 117 118 119]]]


  [[[120 121 122 123 124 125]
    [126 127 128 129 130 131]
    [132 133 134 135 136 137]
    [138 139 140 141 142 143]
    [144 145 146 147 148 149]]

   [[150 151 152 153 154 155]
    [156 157 158 159 160 161]
    [162 163 164 165 166 167]
    [168 169 170 171 172 173]
    [174 175 176 177 178 179]]

   [[180 181 182 183 184 185]
    [186 187 188 189 190 191]
    [192 193 194 195 196 1

In [ ]:
# the calculation of all the dimension matrix would be equal to the amount of elements we give

-> axis numnbers keeps changing based on number of dimensions

axis no.           elements
0                  2

0,1                3 X 2

0,1,2              4 X 3 X 2

0,1,2,3.           5 X 4 X 3 X 2


--> axis numbers are kind of index numbers to the reshape function

-> As long as the shapes/sizes are same on same axis, we can perform arithmetic operations on arrays. 
-> There is also broadcasting on arrays for different sized arrays or sizes. 

In [22]:
data = np.arange(24).reshape(2,3,4)
print(data)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
data.sum()

276

In [24]:
dataaxis0 = data.sum(axis = 0)
print(dataaxis0)
# this is collapsing the axis, the axis 0 here is collapsed and the shape now is (3,4)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [25]:
dataaxis1 = data.sum(axis = 1)
print(dataaxis1)

[[12 15 18 21]
 [48 51 54 57]]


In [27]:
dataaxis2 = data.sum(axis = 2)
print(dataaxis2)

[[ 6 22 38]
 [54 70 86]]


In [29]:
data1 = np.arange(120).reshape(2,3,4,5)
print(data1)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [37]:
dataax0 = data1.sum(axis = 0)
print(dataax0)
dataax0.shape

[[[ 60  62  64  66  68]
  [ 70  72  74  76  78]
  [ 80  82  84  86  88]
  [ 90  92  94  96  98]]

 [[100 102 104 106 108]
  [110 112 114 116 118]
  [120 122 124 126 128]
  [130 132 134 136 138]]

 [[140 142 144 146 148]
  [150 152 154 156 158]
  [160 162 164 166 168]
  [170 172 174 176 178]]]


(3, 4, 5)

In [36]:
dataax1 = data1.sum(axis = 1)
print(dataax1)
dataax1.shape

[[[ 60  63  66  69  72]
  [ 75  78  81  84  87]
  [ 90  93  96  99 102]
  [105 108 111 114 117]]

 [[240 243 246 249 252]
  [255 258 261 264 267]
  [270 273 276 279 282]
  [285 288 291 294 297]]]


(2, 4, 5)

In [35]:
dataax2 = data1.sum(axis = 2)
print(dataax2)
dataax2.shape

[[[ 30  34  38  42  46]
  [110 114 118 122 126]
  [190 194 198 202 206]]

 [[270 274 278 282 286]
  [350 354 358 362 366]
  [430 434 438 442 446]]]


(2, 3, 5)

In [34]:
dataax3 = data1.sum(axis = 3)
print(dataax3)
dataax3.shape

[[[ 10  35  60  85]
  [110 135 160 185]
  [210 235 260 285]]

 [[310 335 360 385]
  [410 435 460 485]
  [510 535 560 585]]]


(2, 3, 4)

# Basic indexing and slicing

In [39]:
import numpy as np

arr1 = np.arange(120).reshape(4,5,6)
print(arr1)
# 4 elements on axis 0, 5 elements on axis 1, 6 elements on axis 2 

[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]
  [ 24  25  26  27  28  29]]

 [[ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]
  [ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]
  [ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]
  [ 84  85  86  87  88  89]]

 [[ 90  91  92  93  94  95]
  [ 96  97  98  99 100 101]
  [102 103 104 105 106 107]
  [108 109 110 111 112 113]
  [114 115 116 117 118 119]]]


In [40]:
arr1[1]

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [41]:
arr1[1][3]

array([48, 49, 50, 51, 52, 53])

In [50]:
arr1[1][3][5]

53

In [51]:
arr1[1,3,-1]  # we can also use all axis in same square brackets with comma in between 

53

In [45]:
arr1[1:3]

array([[[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

In [47]:
arr1[1:3,1:3]

array([[[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77]]])

In [52]:
arr1[1:3,1:3,2:4]

array([[[38, 39],
        [44, 45]],

       [[68, 69],
        [74, 75]]])

In [53]:
# axes are integer indexed
# elements on each axed are also integer indexed 

In [55]:
arr1[:,3:,3:]

array([[[ 21,  22,  23],
        [ 27,  28,  29]],

       [[ 51,  52,  53],
        [ 57,  58,  59]],

       [[ 81,  82,  83],
        [ 87,  88,  89]],

       [[111, 112, 113],
        [117, 118, 119]]])

# we can mix and match both indexing and slicing to get necessary elements 

In [62]:
arr1[2,3:,3:]

array([[81, 82, 83],
       [87, 88, 89]])

In [63]:
arr1[2,3,4:]

array([82, 83])

In [64]:
# In lists: 
# 1. when doing assignment on list slices, the number of elements assigned need not be same as the length of elements 
# being replaced
# 2. The assigned values should be in an iterable

In [ ]:
# whild doing array slice assignment, the above rules do not apply. 

In [65]:
arr2 = np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [66]:
arr2[2:4] = 12
print(arr2)
# here each element in the slicing range gets replaced by 12 
# or we can give equal length of elements to be replaced 

[ 1  2 12 12  5]


In [67]:
arr2[:] = 5

print(arr2)

[5 5 5 5 5]


In [69]:
arr2[0:4] = 1,2,3,4  # given in form of tuple
print(arr2)

[1 2 3 4 5]


# slice assignment in 2D array - Broadcasting

In [70]:
arr3 = np.arange(12).reshape(4,3)
print(arr3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [71]:
arr3[1:3,:2]

array([[3, 4],
       [6, 7]])

In [73]:
arr3[1:3,:2] = np.array([[33,44],[66,77]]) # the dimensions has to match or should be a scalar

In [74]:
print(arr3)

[[ 0  1  2]
 [33 44  5]
 [66 77  8]
 [ 9 10 11]]


In [77]:
arr3[1:3,:2] = 5
print(arr3)

[[ 0  1  2]
 [ 5  5  5]
 [ 5  5  8]
 [ 9 10 11]]


-- > In broadcasting, while doing arithmetic on arrays, we either use a scalar value or array with same shape. 


In [80]:
ar = np.arange(4).reshape(4,1)
print(ar)
ar.shape

[[0]
 [1]
 [2]
 [3]]


(4, 1)

In [81]:
ar = np.arange(4).reshape(1,4,1)
print(ar)
ar.shape

[[[0]
  [1]
  [2]
  [3]]]


(1, 4, 1)

-> even if one of the pattern is mismatched while performing arithmetic, the operation does'nt work and is error


RULES:
-->1. BROADCASTING CAN BE DONE ON ARRAYS AS LONG AS THE LENGTH OF ELEMENTS ON ANY PARTICULAR DIMENSION IS EITHER THE SAME OR 1. 

-->2. INCASE THE NUMBER OF DIMENSIONS OF THE ARRAYS BEING BROADCASTED TOGETHER IS NOT THE SAME. THE SMALLER ARRAY GETS 1 PREPENDED ON EACH DIMENSION THAT IS SHORT 
ex, when array is (3,) and the to be added array is (2,4,3), then the added array is (1,1,3)
(note: the scalar 1 is always prepended and never appended, if it had to append then it's an error and operation cannot be performed)

-->3. OUTPUT SHAPE WILL ALWAYS BE THE SAME AS THE LARGER OF THE TWO ARRAYS BEING BROADCASTED. 

In [83]:
arr1 = np.arange(24).reshape(2,3,4)

print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [87]:
arr2 = np.arange(4)
print(arr2)

[0 1 2 3]


In [88]:
arr1 + arr2

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[12, 14, 16, 18],
        [16, 18, 20, 22],
        [20, 22, 24, 26]]])

In [89]:
arr2 = np.arange(12).reshape(3,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [90]:
arr1 + arr2

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [93]:
arr2 = np.arange(8).reshape(2,1,4)
print(arr2)

[[[0 1 2 3]]

 [[4 5 6 7]]]


In [94]:
arr1 + arr2

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[16, 18, 20, 22],
        [20, 22, 24, 26],
        [24, 26, 28, 30]]])

In [96]:
# To get the same array but 3 dimensional
ar = np.arange(12)
print(ar)
arr = np.arange(12).reshape(1,1,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]]


# Boolean indexing: 

In [98]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [100]:
print(arr1 * 100)

[  0 100 200 300 400 500 600 700 800 900]


In [104]:
print(arr1 > 5)

[False False False False False False  True  True  True  True]


In [105]:
arr1 = np.array([101,120,38,394,75,1004])
print(arr1)

[ 101  120   38  394   75 1004]


In [107]:
arr1 > 100 # shows true or false

array([ True,  True, False,  True, False,  True])

In [106]:
arr1[arr1>100] # only values corresponding to true are returning

array([ 101,  120,  394, 1004])

In [114]:
names = np.array(['Bob', 'John', 'steve', 'will', 'Bob', 'steve', 'Bob'])
print(names)

['Bob' 'John' 'steve' 'will' 'Bob' 'steve' 'Bob']


In [115]:
print(names == "Bob")

[ True False False False  True False  True]


In [116]:
names_bool = names == "Bob"
print(names_bool)

[ True False False False  True False  True]


In [118]:
data = np.random.randint(1, 10, 7)
print(data)

[3 5 6 6 7 3 8]


In [119]:
data[names_bool]

array([3, 7, 8])

In [120]:
data = np.arange(49).reshape(7,7)
print(data)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [121]:
data[names_bool] # it applies to 0 axis 
# note that names_bool have 7 elements and the pattern should match

array([[ 0,  1,  2,  3,  4,  5,  6],
       [28, 29, 30, 31, 32, 33, 34],
       [42, 43, 44, 45, 46, 47, 48]])

In [122]:
data[:, names_bool] # it applies to 1 axis here. 

array([[ 0,  4,  6],
       [ 7, 11, 13],
       [14, 18, 20],
       [21, 25, 27],
       [28, 32, 34],
       [35, 39, 41],
       [42, 46, 48]])

In [124]:
data[names_bool, names_bool] # why is this doing a diagonal?? 

array([ 0, 32, 48])

In [128]:
data[names_bool,:][:,names_bool]

array([[ 0,  4,  6],
       [28, 32, 34],
       [42, 46, 48]])

In [129]:
data = np.arange(42).reshape(2,3,7)
print(data)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]


In [130]:
data[:,:,names_bool]

array([[[ 0,  4,  6],
        [ 7, 11, 13],
        [14, 18, 20]],

       [[21, 25, 27],
        [28, 32, 34],
        [35, 39, 41]]])

# Here for broadcasting the values of names_bool in data, we need to have a pattern match with the array, if the pattern doesn't match, then the broadcasting on slicing doesn't work 

In [148]:
list1 = [1,2,3,4]
np_array = np.array(list1)
np_asarray = np.asarray(list1)
#list1[0] = 11
print(np_array)
print(type(np_array))

print(np_asarray)
print(type(np_asarray))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [149]:
a = np.array([2,3,4,5])

np_array = np.array(a)
a[0] = 11
print(np_array) # does not reflect the changes made in original array

np_asarray = np.asarray(a)
a[0] = 11
print(np_asarray) # does reflect the changes made to original array

[2 3 4 5]
[11  3  4  5]


# Homogenous n- dimensional vectors:

In [151]:
np_zeros = np.zeros(10)
print(np_zeros)

[0 0 0 0 0 0 0 0 0 0]


In [152]:
np_zeros = np.zeros(10, dtype = int)
print(np_zeros)

[0 0 0 0 0 0 0 0 0 0]


In [156]:
np_zero1 = np.zeros([2,3])
print(np_zero1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [157]:
np_one = np.ones(10)
print(np_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [159]:
np_one1 = np.ones((2,3,4),dtype = int)
print(np_one1)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [160]:
# Two parameters are important, first is the number of elements and second is what the value should be

np_full = np.full(10,5) 
print(np_full)

[5 5 5 5 5 5 5 5 5 5]


In [162]:
np_full_a = np.full([2,3], "a")
print(np_full_a)

[['a' 'a' 'a']
 ['a' 'a' 'a']]


In [163]:
np_full_5 = np.full((2,3,4), 5)
print(np_full_5)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [166]:
np_nan = np.full(10, None)
print(np_nan)
print(type(np_nan[0])) # checking dtype of element in the array, not the array itself

[None None None None None None None None None None]
<class 'NoneType'>


In [168]:
np_empty = np.empty(10)
print(np_empty) # takes garbage values

[2.1312229e-314 2.1312229e-314 2.1312229e-314 2.1312229e-314
 2.1312229e-314 2.1312229e-314 2.1312229e-314 2.1312229e-314
 2.1312229e-314 2.1312229e-314]


In [176]:
np_empty1 = np.empty((3,2))
print(np_empty1)
# takes any garbage values

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [177]:
# Identity matrix is matrix of size nXn with ones on the diagonal and zeros elsewhere

In [181]:
np_id_int = np.identity(5, dtype = int)
print(np_id_int)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [180]:
np_id = np.identity(5, dtype = bool)
print(np_id)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [183]:
np_eye = np.eye(5, dtype = int)
print(np_eye)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [186]:
# one difference between identity and eye matrix function is, with eye we can create an assymmetric identity 
# matrix. It is not a proper identity matrix
np_eye_asym = np.eye(5,4, dtype = int)
print(np_eye_asym)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [187]:
np_eye = np.eye(5, dtype = int, k = 1)
print(np_eye)
# here k is which index we want the diagonal to start from

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [188]:
np_eye = np.eye(5, dtype = int, k = -2)
print(np_eye)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


eye matrix can only be done in 2 dimension, so instead of specifying k to shift the diagonal, it can be given directly after the second dimension too.
--> k=1 shifts the diagonal element to 1 side above from diagonal, whereas k = -1 shifts the diagonal element to 1 side below it 

In [191]:
np_eye_d = np.eye(6,6,-1, dtype = int)
print(np_eye_d)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [192]:
list1 = [1,5,7,3,2,9]

np_diag = np.diag(list1)
print(np_diag)

# we need not specify any dimensions here. it's taken according to given list of elements

[[1 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 9]]


In [193]:
np_diag1 = np.diag(list(range(10)))
np_diag1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [202]:
np_num = np.arange(25).reshape(5,5)
print(np_num)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [203]:
np_diag = np.diag(np_num)
print(np_diag)

[ 0  6 12 18 24]


In [205]:
np_diag = np.diag(np_num, k = -2)
print(np_diag)

[10 16 22]


In [207]:
np_asm = np.arange(32).reshape(4,8)
print(np_asm)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [210]:
np_diag = np.diag(np_asm, k = 3)
print(np_diag)

# can be used on asymmetric matrices as well

[ 3 12 21 30]


From function:
-> create an array by executing a function over each coordinates. let's create a vector based on its indices: 

-> for fromfunction, we cannot supply an array, we have to supply a shape. so the array shape that we provide is taken as the coordinates equvivalent to x,y

In [211]:
np_fromf = np.fromfunction(lambda x,y : x-y, (3,3), dtype = int)
print(np_fromf)

[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


In [216]:
np_ff = np.fromfunction(lambda x : x*5, (3,), dtype = int)
print(np_ff)

[ 0  5 10]


In [218]:
np_ff = np.fromfunction(lambda x,y : x*2+y*3, (3,5), dtype = int)
print(np_ff)

[[ 0  3  6  9 12]
 [ 2  5  8 11 14]
 [ 4  7 10 13 16]]


In [219]:
np_ff = np.fromfunction(lambda x,y,z : x+y, (3,4,5), dtype = int)
print(np_ff)

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]
  [5 5 5 5 5]]]


In [220]:
np_sample = np.arange(12).reshape(3,4)
print(np_sample)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [226]:
# otherway to do sum 
np_sum = np.sum(np_sample, axis = 1)
print(np_sum)
# one way
print(np_sample.sum(axis = 1))

[ 6 22 38]
[ 6 22 38]


similarly, np.prod() gives the product of two arrays

In [229]:
np_sample = np.arange(1,7).reshape(2,3)
print(np_sample)

[[1 2 3]
 [4 5 6]]


In [230]:
np_prod = np_sample.prod()
print(np_prod)

720


In [233]:
np_prod1 = np_sample.prod(axis = 1)
print(np_prod1)

[  6 120]


In [235]:
np_prod0 = np_sample.prod(axis = 0)
print(np_prod0)

[ 4 10 18]


In [236]:
np_sample = np.arange(1,25).reshape(2,3,4)
print(np_sample)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [238]:
np_prod1 = np_sample.prod(axis = 0)
print(np_prod1)

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [241]:
np_prod1 = np_sample.prod(axis = 2)
print(np_prod1)
np_prod1 = np_sample.prod(0) # we don't need to specify the keyword axis inside the prod function in numpy.. 
print(np_prod1)

[[    24   1680  11880]
 [ 43680 116280 255024]]
[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


In [242]:
np_arr = np.arange(100).reshape(4,5,5)
print(np_arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [244]:
np_flat = np_arr.flatten()
print(np_flat)

# flatten() takes an array of any dimension and converts it to 1 D array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


ndarray.max : Return the maximum along the given axis


ndarray.argmax : Return indices of the maximum values along the given axis

In [249]:
arr1 = np.random.randint(1,100,24).reshape(2,3,4)
print(arr1)

[[[68 53 89 39]
  [71 83 65 88]
  [73 82 50 22]]

 [[91 64 64 40]
  [16 59  9 22]
  [65 99 93 31]]]


In [250]:
print(arr1.max())

99


In [251]:
print(arr1.argmax()) # argmax() automatically flattens the array and then provides the index of the maximum
# element of the array

21


In [252]:
print(arr1.max(0))

[[91 64 89 40]
 [71 83 65 88]
 [73 99 93 31]]


In [253]:
print(arr1.max(1))

[[73 83 89 88]
 [91 99 93 40]]


In [254]:
print(arr1.max(2))

[[89 88 82]
 [91 59 99]]


# argmax() along the axis of an array compares indexes along the axis and gives the index number of the elements in the particular axis 

# argmax() only flattens the array if the axis number is not provided

In [255]:
print(arr1.argmax(0))

[[1 1 0 1]
 [0 0 0 0]
 [0 1 1 1]]


In [256]:
print(arr1.argmax(1))

[[2 1 0 1]
 [0 2 2 0]]


In [257]:
print(arr1.argmax(2))

[[2 3 1]
 [0 1 1]]


-> Axis numbers are integer indexed.
-> Elements along the axis are also integer indexed

  # mean

In [258]:
print(arr1)

[[[68 53 89 39]
  [71 83 65 88]
  [73 82 50 22]]

 [[91 64 64 40]
  [16 59  9 22]
  [65 99 93 31]]]


In [259]:
print(arr1.mean())  # mean of all the elements on all axis

59.833333333333336


In [264]:
print(arr1.mean(0))


[[79.5 58.5 76.5 39.5]
 [43.5 71.  37.  55. ]
 [69.  90.5 71.5 26.5]]


In [263]:
print(arr1.mean(1))

[[70.66666667 72.66666667 68.         49.66666667]
 [57.33333333 74.         55.33333333 31.        ]]


In [265]:
print(arr1.mean(2))

[[62.25 76.75 56.75]
 [64.75 26.5  72.  ]]


In [266]:
# ndarray.cumsum() : returns the cummulative sum of the elements along the given axis

In [267]:
arr = np.random.randint(1,10,24).reshape(2,3,4)
print(arr)

[[[5 6 4 5]
  [9 1 1 5]
  [5 9 9 5]]

 [[6 7 7 7]
  [3 8 5 8]
  [4 1 6 5]]]


In [268]:
print(arr.cumsum())

# cumsum along NO axis also flattens the array(like argmax()) and gives the cummulative sum

[  5  11  15  20  29  30  31  36  41  50  59  64  70  77  84  91  94 102
 107 115 119 120 126 131]


In [269]:
print(arr.cumsum(0))

[[[ 5  6  4  5]
  [ 9  1  1  5]
  [ 5  9  9  5]]

 [[11 13 11 12]
  [12  9  6 13]
  [ 9 10 15 10]]]


In [270]:
print(arr.cumsum(1))

[[[ 5  6  4  5]
  [14  7  5 10]
  [19 16 14 15]]

 [[ 6  7  7  7]
  [ 9 15 12 15]
  [13 16 18 20]]]


In [271]:
print(arr.cumsum(2))

[[[ 5 11 15 20]
  [ 9 10 11 16]
  [ 5 14 23 28]]

 [[ 6 13 20 27]
  [ 3 11 16 24]
  [ 4  5 11 16]]]


In [272]:
arr2 = np.random.randint(1,3,24).reshape(2,3,4)
print(arr2)

[[[2 2 2 1]
  [2 2 1 1]
  [2 2 1 1]]

 [[1 2 1 2]
  [1 2 1 2]
  [2 1 2 2]]]


In [273]:
print(arr2.cumprod())

[    2     4     8     8    16    32    32    32    64   128   128   128
   128   256   256   512   512  1024  1024  2048  4096  4096  8192 16384]


In [274]:
print(arr2.cumprod(0))

[[[2 2 2 1]
  [2 2 1 1]
  [2 2 1 1]]

 [[2 4 2 2]
  [2 4 1 2]
  [4 2 2 2]]]


In [ ]:
# variance gives the total variance of the dat

# standard deviation is square root of variance and tells how far the value is from the mean.

In [275]:
print(arr)

[[[5 6 4 5]
  [9 1 1 5]
  [5 9 9 5]]

 [[6 7 7 7]
  [3 8 5 8]
  [4 1 6 5]]]


In [278]:
print(arr.var()) # to calculate variance
print('-'*50)
print(arr.std()) # to calculate standard deviation

5.414930555555556
--------------------------------------------------
2.327000334240534


# arithmetic functions in numpy: 

add, subtract, multiply, divide, power, remainder,mod, mean, average, sum, prod, var, std

In [281]:
np_arr = np.arange(1,10,2)
print(np_arr)

[1 3 5 7 9]


In [283]:
lst1 = list(range(1.1,10.2, 0.2))
print(lst1)

TypeError: 'float' object cannot be interpreted as an integer

In [287]:
np_arr = np.arange(1.2,10.2,0.2)
print(np_arr)
# in arange we can do float elements

[ 1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6  3.8
  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4  6.6
  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4
  9.6  9.8 10. ]


In [288]:
# arange allows to get range of data - it allows integers, floats and datetime64

In [289]:
np_arr_dec = np.arange(1.1,10.2,0.2, dtype = int)
print(np_arr_dec)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


1.1 + 0.2 = 1.3 -> 1+0.2 =1.2 -> 1 ...............

-> linspace - gives equal number of data points between the specified range. (by default it makes it 50 unless specified)
->
It takes 7 arguments:
1. start - mandatory
2. stop - mandatory
3. num - optional - number of samples required between the given range
4. endpoint - optional - by default set to true and includes the endpoint(stop value) - if set ot false, returns equidistant numbers not including the stop value
5. retstep - optional - default is false. if set to true, returns the samples and the step value (distance between samples)
6. dtype - optional - by default datatype is inferred. however, for int dtype , float will be considered even if the start and stop are int
7. axis - optional - By default 0 axis, Only useful in case start and stop are ARRAY-LIKE


In [290]:
arr_lin = np.linspace(1,50)
print(arr_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [295]:
arr_lin = np.linspace(1,100)
print(arr_lin)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [296]:
arr_lin = np.linspace(1,100,100)
print(arr_lin)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


In [307]:
lin = np.linspace(1,18,5,retstep = True, dtype = int) # specified dtype
print(lin)

(array([ 1,  5,  9, 13, 18]), 4.25)


In [302]:
lin_arr = np.linspace((1,2),(3,4), 10, axis = 1) # array like start and stop values
print(lin_arr)

[[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
  2.33333333 2.55555556 2.77777778 3.        ]
 [2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
  3.33333333 3.55555556 3.77777778 4.        ]]


In [308]:
lin_arr = np.linspace((1,2,5),(3,4,10), 10) 
# with equidistant samples added along axis 1
print(lin_arr)

[[ 1.          2.          5.        ]
 [ 1.22222222  2.22222222  5.55555556]
 [ 1.44444444  2.44444444  6.11111111]
 [ 1.66666667  2.66666667  6.66666667]
 [ 1.88888889  2.88888889  7.22222222]
 [ 2.11111111  3.11111111  7.77777778]
 [ 2.33333333  3.33333333  8.33333333]
 [ 2.55555556  3.55555556  8.88888889]
 [ 2.77777778  3.77777778  9.44444444]
 [ 3.          4.         10.        ]]


In [309]:
lin_arr = np.linspace((1,2,5),(3,4,10), 10, axis = 1) 
print(lin_arr)

[[ 1.          1.22222222  1.44444444  1.66666667  1.88888889  2.11111111
   2.33333333  2.55555556  2.77777778  3.        ]
 [ 2.          2.22222222  2.44444444  2.66666667  2.88888889  3.11111111
   3.33333333  3.55555556  3.77777778  4.        ]
 [ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
   8.33333333  8.88888889  9.44444444 10.        ]]


# Random module

In [310]:
rand = np.random.randint(1,10)
print(rand)

4


In [312]:
rand = np.random.randint(1,100,25) # any random 25 numbers between 1 and 100
print(rand)

[25 42 27 96 90  7 50 75 35 56 25 96 20 11 44 73 95 27 39 16 92 53 60 20
 88]


In [313]:
rand = np.random.randint(1,100,(2,3,4))
print(rand)

[[[ 8  7 71 55]
  [19 45 72 15]
  [61 78 53 28]]

 [[70 99 49  9]
  [44 68 78 54]
  [47 52 90 57]]]


In [319]:
np.random.seed(42)  # setting the seed 

# restarting the kernal also gives the same output as before - does not change
# it will choose random numbers but the result will be smae always even if we execute 
# multiple times

result = np.random.randint(1,100,10)
print(result)

[52 93 15 72 61 21 83 87 75 75]


In [322]:
np.random.seed(100) # different for other numbers provided
# multiple times

result = np.random.randint(1,100,10)
print(result)

[ 9 25 68 88 80 49 11 95 53 99]


In [ ]:
# most common/ prominent seed values used - 41,42,101

In [324]:
result = np.random.rand(3)
print(result)
# gives random float values between 0 and 1 only

[0.87014264 0.06368104 0.62431189]


In [326]:
res = np.random.rand(2,3,4) # we can give any dimensions/ shapes 
print(res)

[[[0.17582131 0.11830284 0.86294567 0.07486688]
  [0.82509486 0.83613181 0.07539491 0.01140079]
  [0.04842057 0.35712271 0.66569338 0.01138961]]

 [[0.10791777 0.9010131  0.79487876 0.81146098]
  [0.64027806 0.62477951 0.14550751 0.5702159 ]
  [0.0651125  0.31341257 0.21706577 0.52695039]]]


In [327]:
res = np.random.uniform(1,10,20)
print(res) # gives random float values in specified range

[4.84397544 9.84367384 2.26406338 7.73570444 8.09956354 7.57356954
 8.61056505 6.00571341 1.5117644  8.98052109 3.82975255 6.04352681
 3.28612956 9.41465894 1.30820449 7.1789046  4.95041447 9.79948858
 5.29645738 3.15057369]


In [329]:
uni = np.random.uniform(1.5,10.2,(2,3,4))
print(uni)

[[[6.37586855 8.61142578 2.27435478 7.60294323]
  [4.85447746 1.65157614 1.94341177 5.28512413]
  [9.99854164 2.31591479 6.29821967 7.09499734]]

 [[5.3302153  8.36320225 7.62878059 7.76798775]
  [5.82195758 7.8822815  9.10843283 6.37112491]
  [7.41960769 4.70534837 6.64282052 5.66784587]]]


#randn function - returns float value in given shape array from a standard normal distribution

- roughly - 68% of the values will be between -1 and 1
- roughly - 95% of the values will be between -2 to 2 , -2 to -1 and 1 to 2 - 27%
- roughly - 99.2% of the values will be between -3 to 3, -3 to -2 and 2 to 3 - 4.4%
- roughly - 99.7% of the values will be between -4 to 4

--> if no shape is provided, then returns a single float value


In [332]:
result = np.random.randn(100)
print(result)
# most numbers are between -1 and +1
# few number are between -2 and +2

[-1.19449029  1.60006235  0.03034095  0.79741515 -1.69141624  0.18864899
 -0.53753902  1.18086752 -0.61283947  0.06771082 -0.80731712 -0.16578194
 -0.90964037 -0.79326307 -1.38071781 -1.17836855  0.76838023 -0.60754502
 -0.7473156  -0.03190527 -0.46610165  1.53819322  0.3884666  -0.58598598
  0.73764019 -0.12301387 -0.90326898  1.07150781  2.12449687  0.5003683
  0.7003502   0.68084914  0.99163248  0.50305299 -2.59375089  0.24520242
  0.74054808 -0.03876821 -0.7220084  -0.40778889  0.2888535  -0.76055434
  1.49598592  1.10385714 -0.27414307  0.47094189  1.23170938  0.77889302
  0.11176924 -2.15208448 -0.08576961 -1.6489635   0.28079931  1.34850343
 -2.02941188 -0.57744644 -1.25801562  0.53962509 -0.12265801 -1.09427418
 -1.31741355 -0.42618677  0.01417164  0.28615794 -0.34558302 -0.57606667
 -0.43424511 -1.52483797 -1.08618346  0.68753616  1.70494853  0.47312829
 -0.2924172  -0.71736812 -3.45479771  0.33157503  0.05880897  0.5867991
 -0.81516944  1.69668659  0.34530229  0.56905008  1.6

In [334]:
result = np.random.randn(2,5,10)
print(result)

[[[ 1.14275202  0.61200288 -0.12353239  0.89841359  0.84066248
   -0.8588119   1.21470866  0.89352328 -1.1052896   0.51126955]
  [-0.01488769 -0.10527878 -0.93249484 -0.04303337  0.8099778
   -1.97966066  0.1882086  -0.57130504 -0.34097129  0.11774248]
  [-1.05473169  1.27863458  0.04078279 -1.30540397 -0.08391699
   -0.33403439  0.13228139 -0.82637032  0.94484211  0.72613475]
  [ 1.48007469  0.10665599 -0.93742322 -0.72903822  0.93216733
   -1.46759396  0.50476332  0.09201342  0.49002191  1.73493511]
  [ 1.23690069 -0.76966696  0.49513669 -0.33837865 -0.16876304
    1.1681938   0.98308066  2.84026327  0.22242931  0.96385285]]

 [[-1.12549899 -0.76279707  1.62337759 -0.92625324  2.10248889
    0.78485237  0.48482435  0.97837034 -0.42146076  0.08870573]
  [-0.56025761  0.35518798 -0.65209669 -0.07583802  0.28382974
    0.72234857 -0.05688487  0.95883093  0.13304343  0.55577644]
  [ 0.34077302  0.45734124 -1.12220579  0.09336404  2.23987823
   -0.5628291  -0.08246473  1.19941757 -1.65343

In [335]:
arr1 = np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [336]:
# choice =  choose a random number from an array or integer range

# takes only an array or an integer value(chooses from 0 to the integer value number) as input from which 
# to choose

choice = np.random.choice(arr1, 10)
print(choice)

[21 39 43 11 38 36 26 22 43 14]


In [339]:
choice = np.random.choice(arr1, 20, replace = False) #no repetition

print(choice)
# only till the length of elements to be choosen are within the specified range

[29 34 41 17 45 37 20 44 21 30 39 23 33 43 35 47 10 32 49 42]


In [346]:
# array need not be just integer, an example of string
names = ['yashoda', 'rohan', 'rakesh', 'raghu','mala','Jatin', 'maithali','sachin']

choice = np.random.choice(names, 4)
print(choice)
choice1 = np.random.choice(names, 4, replace = False)
print(choice1)

['raghu' 'raghu' 'rohan' 'rakesh']
['mala' 'sachin' 'rohan' 'Jatin']


In [347]:
# we can give probability for associated to the elements of the array, based on topmost probabilites is how the
# random output is generated

# you might still get the low probability ones at some execution 
# probabilites should sum up to 1
# and probability should be given to every element and positional with "p" keyword

choosename = np.random.choice(names, 10, p = [0.40, 0.2, 0.25, 0.10, 0.01, 0.02, 0.01, 0.01])
print(choosename)

['rakesh' 'yashoda' 'Jatin' 'yashoda' 'yashoda' 'yashoda' 'rakesh' 'Jatin'
 'yashoda' 'rakesh']


In [349]:
# permutation is different /various ways of arranging elements

perm = np.random.permutation(10) # here is re-arrangement of given elements 
print(perm)

[7 6 9 2 4 5 8 3 1 0]


In [351]:
arr1 = np.random.randint(1,20,6)
print(arr1)

[16 19  8 11 15 18]


In [353]:
perm1 = np.random.permutation(arr1)
print(perm1)

[15  8 19 18 11 16]


In [354]:
np_arr = np.arange(20,40)
print(np_arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [357]:
perm = np.random.permutation(np_arr)
print(perm)

[25 36 27 21 29 22 37 31 24 33 20 30 32 38 35 23 28 34 26 39]


In [358]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [359]:
perm_arr = np.random.permutation(arr)
print(perm_arr)
# while using on 0 axis, it always permutates on 0 axis and not on any other axis as per internal function code 
# written - if still needed, we need to write differnt programming logic

[[[18 19]
  [20 21]
  [22 23]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]]


In [360]:
arr_perm = np.arange(24).reshape(2,3,4)
print(arr_perm)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [362]:
# to anyway permutate a multi- dimensional array, we can flatten it and make a random permutation using reshape 
# with permutation function
perm_arr1 = arr_perm.flatten()
perm_arr2 = np.random.permutation(perm_arr1).reshape(2,3,4)
print(perm_arr2)

[[[13  8  2 16]
  [10  5  6 18]
  [22  1 19 12]]

 [[21 17  7  0]
  [11  3 15  4]
  [14  9 20 23]]]


In [ ]:
# any - returns true if any of the elements in the array are true
# all - returns true if all the elements in an array are true

In [363]:
arr  = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [364]:
print(np.any(arr))

True


In [365]:
print(np.all(arr))

False


In [367]:
arr1 = np.arange(11)
arr2 = np.arange(11,21)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [368]:
arr_append = np.append(arr1,arr2)
print(arr_append)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [369]:
# in lists, there is no return from the append function.
# In numpy arrays, there is a return from append

In [380]:
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr3 = np.arange(101,251,10).reshape(3,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [381]:
print(arr2)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [382]:
print(arr3)

[[101 111 121 131 141]
 [151 161 171 181 191]
 [201 211 221 231 241]]


In [383]:
arr_1n2 = np.append(arr1,arr2, axis = 0)
print(arr_1n2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [387]:
arr_1n3 = np.append(arr1,arr3, axis = 0)
print(arr_1n3)
# though arr3 has 3,5 instead of 2,5, since we are appending on 0 axis, it works

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [101 111 121 131 141]
 [151 161 171 181 191]
 [201 211 221 231 241]]


In [388]:
arr_1n2 = np.append(arr1,arr2, axis = 1)
print(arr_1n2)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


arr_1n3 = np.append(arr1,arr3, axis = 1)
print(arr_1n3)

--> it does not match the axis 1

In [390]:
# vstack stacks the arrays vertically, like appending on axis 0

In [391]:
arrv = np.vstack((arr1,arr2))
print(arrv)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [392]:
arrv = np.vstack((arr1,arr3))
print(arrv)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [101 111 121 131 141]
 [151 161 171 181 191]
 [201 211 221 231 241]]


In [393]:
arr1v = np.arange(1,6)
arr2v = np.arange(11,16)
print(arr1v)
print(arr2v)

[1 2 3 4 5]
[11 12 13 14 15]


In [394]:
arr1v = np.arange(1,13).reshape(2,2,3)
arr2v = np.arange(11,23).reshape(2,2,3)
print(arr1v)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [395]:
print(arr2v)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [396]:
arrvx = np.vstack((arr1v,arr2v))
print(arrvx)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [398]:
arr1h = np.arange(6).reshape(2,3)
arr2h = np.arange(10,16).reshape(2,3)
print(arr1h)
print(arr2h)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


In [399]:
arrhx = np.hstack((arr1h,arr2h))
print(arrhx)

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [402]:
arr1h = np.arange(24).reshape(2,3,4)
arr2h = np.arange(0,240,10).reshape(2,3,4)
print(arr1h)
print(arr2h)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[  0  10  20  30]
  [ 40  50  60  70]
  [ 80  90 100 110]]

 [[120 130 140 150]
  [160 170 180 190]
  [200 210 220 230]]]


In [404]:
arrhx = np.hstack((arr1h,arr2h))
print(arrhx)
# hstack is always working on axis 1, irrespective if there is an axis 2

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  0  10  20  30]
  [ 40  50  60  70]
  [ 80  90 100 110]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]
  [120 130 140 150]
  [160 170 180 190]
  [200 210 220 230]]]


In [409]:
#sort :
# sort will by default sort on innermost/last axis (axis 2 here)

np.random.seed(101)

arr3 = np.random.randint(1,10,20).reshape(2,2,5)
print(arr3)


[[[2 7 8 9 5]
  [9 6 1 6 9]]

 [[2 4 9 4 4]
  [3 9 4 8 1]]]


In [410]:
arr_sort = np.sort(arr3)
print(arr_sort)

[[[2 5 7 8 9]
  [1 6 6 9 9]]

 [[2 4 4 4 9]
  [1 3 4 8 9]]]


In [411]:
arr_sort = np.sort(arr3,axis = 0)
print(arr_sort)

[[[2 4 8 4 4]
  [3 6 1 6 1]]

 [[2 7 9 9 5]
  [9 9 4 8 9]]]


In [408]:
arr_sort = np.sort(arr, axis = 1)
print(arr_sort)

[[[2 6 1 6 5]
  [9 7 8 9 9]]

 [[2 4 4 4 1]
  [3 9 9 8 4]]]


In [412]:
arr_sort = np.sort(arr, axis = 2)
print(arr_sort)

[[[2 5 7 8 9]
  [1 6 6 9 9]]

 [[2 4 4 4 9]
  [1 3 4 8 9]]]


In [413]:
arr_sort = np.sort(arr, axis = -2)  # similar to axis 1 (negative indexing)
print(arr_sort)

[[[2 6 1 6 5]
  [9 7 8 9 9]]

 [[2 4 4 4 1]
  [3 9 9 8 4]]]


In [417]:
# insert:
arr = np.arange(10,100,10)
print(arr)

[10 20 30 40 50 60 70 80 90]


In [418]:
arr_ins = np.insert(arr,2,55)
print(arr_ins)

[10 20 55 30 40 50 60 70 80 90]


In [420]:
arr_ins2 = np.insert(arr_ins,9,555)
print(arr_ins2)

[ 10  20  55  30  40  50  60  70  80 555  90]


In [421]:
arr_ins3 = np.insert(arr_ins2, -1, 22)
print(arr_ins3) # shifts the value of -1 to the last

[ 10  20  55  30  40  50  60  70  80 555  22  90]


In [422]:
arr1 = np.random.randint(1,10,24).reshape(2,3,4)
print(arr1)

[[[8 9 5 4]
  [4 8 5 9]
  [8 7 5 3]]

 [[8 8 8 1]
  [5 2 9 4]
  [2 9 5 4]]]


In [423]:
arr2 = np.random.randint(1,5,12).reshape(3,4)
print(arr2)

[[3 4 3 3]
 [4 1 4 1]
 [4 1 3 3]]


In [424]:
arrins = np.insert(arr1,1,arr2, axis = 0) # insert in array "arr1" at index 1 the "arr2" on axis 0
print(arrins)

[[[8 9 5 4]
  [4 8 5 9]
  [8 7 5 3]]

 [[3 4 3 3]
  [4 1 4 1]
  [4 1 3 3]]

 [[8 8 8 1]
  [5 2 9 4]
  [2 9 5 4]]]


In [426]:
print(arr1)

[[[8 9 5 4]
  [4 8 5 9]
  [8 7 5 3]]

 [[8 8 8 1]
  [5 2 9 4]
  [2 9 5 4]]]


In [425]:
arr3 = np.arange(8).reshape(2,4)
print(arr3)

[[0 1 2 3]
 [4 5 6 7]]


In [428]:
arrins2 = np.insert(arr1, 1,arr3, axis = 1)
print(arrins2)

[[[8 9 5 4]
  [0 1 2 3]
  [4 8 5 9]
  [8 7 5 3]]

 [[8 8 8 1]
  [4 5 6 7]
  [5 2 9 4]
  [2 9 5 4]]]


In [431]:
arr4 = np.arange(6).reshape(2,3)
print(arr4)

[[0 1 2]
 [3 4 5]]


In [433]:
arrins3 = np.insert(arr1,2,arr4, axis = 2)
print(arrins3)

[[[8 9 0 5 4]
  [4 8 1 5 9]
  [8 7 2 5 3]]

 [[8 8 3 8 1]
  [5 2 4 9 4]
  [2 9 5 5 4]]]


In [435]:
# Transposing-  Interchanging the axis
# Transpose gives you a view object, so the original object also changes when any changes are made

In [438]:
arr1 = np.arange(1,9).reshape(2,4)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [440]:
arr2 = arr1.transpose()
print(arr2)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [442]:
arr2[-1][-1] = 88
print(arr2)
print(arr1)

[[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4 88]]
[[ 1  2  3  4]
 [ 5  6  7 88]]


In [443]:
arr = np.arange(1,25).reshape(2,3,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [444]:
arr2 = np.transpose(arr, (1,0,2))
print(arr2)
print(arr2.shape)

[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
(3, 2, 4)


In [445]:
arr3 = np.transpose(arr,(1,2,0))
print(arr3)

[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [448]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [446]:
arr4 = np.transpose(arr,(2,1,0))
print(arr4)

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


# Datetime

--> Takes input as a string.
-> format - "YYYY-MM-DD hh:mm:ss"


In [457]:
import numpy as np
np_date1 = np.datetime64("2023-04-08")

print(np_date1)
print(type(np_date))
# takes string as input and output is datetime object

2023-04-08
<class 'numpy.datetime64'>


In [450]:
np_date = np.datetime64('2023-05-26 01:14:30.09')
print(np_date)
print(type(np_date))
# T shows that it is time 

2023-05-26T01:14:30.090
<class 'numpy.datetime64'>


In [451]:
print(np_date.dtype)

datetime64[ms]


In [452]:
np_date1 = np.datetime64('2023-05-26 01:14:30')
print(np_date1)
print(np_date1.dtype) # datetime object is till seconds

2023-05-26T01:14:30
datetime64[s]


In [453]:
np_date1 = np.datetime64('2023-05')
print(np_date1)
print(np_date1.dtype) # shows that the datetime object is till month("M")

2023-05
datetime64[M]


In [454]:
# we can truncate the datetime object

In [461]:
# can perform arithmetic operations on datetime object
print(np_date1+7)

2023-04-15


In [462]:
np_datet = np.datetime64("2022-09-12 11:20", 'h') # want to only take it till hours and exclude the minutes 
print(np_datet)
print(np_datet.dtype)

2022-09-12T11
datetime64[h]


In [463]:
np_datet = np.datetime64("2022-09-12 11:20", 'M') # till months
print(np_datet)
print(np_datet.dtype)

2022-09
datetime64[M]


In [465]:
np_date2 = np.datetime64('2023-04', 'm') # if we do not specify the exact time and still want to get the output 
# with time it takes first day of month and midnight as default
print(np_date2)

2023-04-01T00:00


In [468]:
np_date = np.datetime64('2023', 'M')
print(np_date)

2023-01


In [469]:
np_date = np.datetime64('2023', 'ms')
print(np_date)

2023-01-01T00:00:00.000


common abbreviations in datetime

Y - years
M - months
D - days
W - weeks
h - hours
m - minutes
s - seconds
ms - milliseconds

In [488]:
np_date = np.datetime64('2023-05-26','W') # don't know what exactly this is doing - seems very weird
print(np_date)

2023-05-25


In [489]:
np_date = np.datetime64('2023-05-25', 'D')
print(np_date)

2023-05-25


In [492]:
print(np_date - 7)

2023-05-18


In [493]:
today = np.datetime64('today')
print(today)

2023-05-26


In [497]:
np_tod = np.datetime64('today', 'm')
print(np_tod)

2023-05-26T00:00


In [502]:
npnew = np_tod + np.timedelta64(5,'D')
print(npnew)

2023-05-31T00:00


In [504]:
npnew = np_tod + np.timedelta64(10,'D')# directly changes the months
print(npnew)

2023-06-05T00:00


In [506]:
np_td = np.timedelta64(5,"D") #adding days
print(np_td)
print(type(np_td))
print(np_td.dtype)

5 days
<class 'numpy.timedelta64'>
timedelta64[D]


In [507]:
np_td = np.timedelta64(5,"m") # adding minutes - we can still do if no time or hours or given
print(np_td)
print(type(np_td))
print(np_td.dtype)

5 minutes
<class 'numpy.timedelta64'>
timedelta64[m]


In [ ]:
# Timedelta64 - does not work between datetime64 object of unit between day(or lower) and year/month

In [508]:
np_timed = np_tod + np.timedelta64(1,"Y")
print(np_timed)

UFuncTypeError: Cannot cast ufunc 'add' input 1 from dtype('<m8[Y]') to dtype('<m8[m]') with casting rule 'same_kind'

In [ ]:
# is_busday function - tells whether business day or not
# takes datetime object

In [509]:
np_isbusday = np.is_busday(np.datetime64('2023-05-26'))
print(np_isbusday)

True


In [510]:
np_isbusday = np.is_busday(np.datetime64('2023-05-27'))
print(np_isbusday)

False


weekmask = [1,1,1,1,1,0,0]
weekmask = "1111100"
weekmask = 'Mon Tue Wed Thu Fri Sat'

In [511]:
np_isbusday1 = np.is_busday(np.datetime64('2023-05-27'), weekmask = [1,1,1,1,1,1,0]) # changing the busday
print(np_isbusday1)

True


In [513]:
aprdates = np.arange('2023-04-01', '2023-05-01', dtype = 'datetime64')
print(aprdates)
print(type(aprdates[0]))
print(aprdates[0].dtype)

['2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30']
<class 'numpy.datetime64'>
datetime64[D]


In [514]:
satsunNO = np.is_busday(aprdates, weekmask = [0,0,0,0,0,1,1])
print(satsunNO)

[ True  True False False False False False  True  True False False False
 False False  True  True False False False False False  True  True False
 False False False False  True  True]


In [515]:
print(aprdates[satsunNO]) # getting only weekends/ business or non-business days

['2023-04-01' '2023-04-02' '2023-04-08' '2023-04-09' '2023-04-15'
 '2023-04-16' '2023-04-22' '2023-04-23' '2023-04-29' '2023-04-30']


In [517]:
busday_count = np.busday_count('2023-05-01', '2023-06-01')
print(busday_count)

23


In [ ]:
# specified dates can be passed as holiday as array object

In [518]:
#busdayoffset- next business day

busday_offset = np.busday_offset('2023-05-26', 1)
print(busday_offset)

2023-05-29


In [519]:
busday_offset = np.busday_offset('2023-05-26', 1, roll = 'forward')
print(busday_offset)

2023-05-29


In [526]:
busday_offset = np.busday_offset('2023-05-26', -3) # 3 days before
print(busday_offset)
busday_offset = np.busday_offset('2023-05-26', -3, roll = 'backward') # 3 days before
print(busday_offset)

2023-05-23
2023-05-23
